import { Employee } from "@/types/services/humanResources/employee"

export function createMockEmployee(overrides: Partial<Employee> = {}): Employee {
	return {
		id: "1",
		name: "Colaborador Teste",
		sex: "M",
		birthday: "01/01/1990",
		civilState: "SINGLE",
		rg: "12.345.678-9",
		cpf: "123.456.789-01",
		email: "teste@ts.com",
		motherName: "Mãe Teste",
		phone: "+55 (11) 99999-9999",
		city: "São Paulo",
		postalCode: "01000-000",
		street: "Rua Teste",
		neighborhood: "Centro",
		workCard: "123456",
		pisPasep: "123.45678.90-1",
		typeEmployment: "CLT",
		laborModality: "IN_PERSON",
		laborScale: "_5X2",
		admissionDate: "01/01/2024",
		salary: 5000,
		residentialProve: "",
		reservist: false,
		documentation: "",
		bank: "SANTANDER",
		agency: 1234,
		account: 56789,
		pix: "teste@ts.com",
		transportationVoucher: false,
		cnpjTransportationVoucher: "",
		monthlyAmount: null,
		additionalDocuments: [],
		department: "AUDIOVISUAL",
		operation: "_01",
		level: "JUNIOR_EAGLE",
		status: "ACTIVE",
		quitDate: "",
		...overrides,
	}
}
