import type { Metadata } from "next"
import "./globals.css"
import { LoginProvider } from "@/contexts/LoginContext"
import { Inter } from "next/font/google"

export const metadata: Metadata = {
  title: "Create Next App", description: "Generated by create next app"
}

const inter = Inter({subsets: ["latin"], variable: "--font-inter"})

const RootLayout = ({ children }: Readonly<{children: React.ReactNode}>) => <html lang="en"><body className={inter.className}><LoginProvider>{ children }</LoginProvider></body></html>

export default RootLayout