import type { Metadata } from "next"
import "./globals.css"
import { LoginProvider } from "@/contexts/LoginContext"

export const metadata: Metadata = {
  title: "Create Next App", description: "Generated by create next app"
}

const RootLayout = ({ children }: Readonly<{children: React.ReactNode}>) => <html lang="en"><body><LoginProvider>{ children }</LoginProvider></body></html>

export default RootLayout