export interface Employee {
    id: string,
    name: string, 
    birthday: string, 
    civilState: "" | "SINGLE" | "MARRIED" | "WIDOWED",
    nacionality: "" | "BRAZILIAN" | "AMERICAN",
    rg: string, 
    cpf: number,
    email: string, 
    motherName: string, 
    phone: number,
    city: string, 
    postalCode: number, 
    street: string, 
    neighborhood: string,
    workCard: number,
    pisPasep: number,
    typeEmployment: "" | "CLT" | "CNPJ" | "FREELANCE",
    laborModality: "" | "IN_PERSON" | "HYBRID" | "HOME_OFFICE",
    laborScale: "" | "_5X2" | "_4X3" | "_6X1",
    admissionDate: string,
    salary: number,
    residentialProve: string,
    reservist: boolean,
    documentation: string,
    bank: "" | "SANTANDER" | "SICRED" | "BANCO_DO_BRASIL",
    agency: number,
    account: number,
    pix: string,
    transportationVoucher: boolean,
    cnpjTransportationVoucher: number,
    monthlyAmount: number,
    additionalDocuments: string,
    department: "" | "RESEARCH_AND_DEVELOPMENT" | "WEB_DESIGN" | "PAID_TRAFFIC",
    operation: "" | "_01" | "_02" | "_03",
    level: "" | "PUPPY" | "ASSISTANT" | "JUNIOR",
    status: "ACTIVE" | "INACTIVE",
    quitDate: string
}

export interface SendEmployee {
    name: string, 
    birthday: string, 
    civilState: "" | "SINGLE" | "MARRIED" | "WIDOWED",
    nacionality: "" | "BRAZILIAN" | "AMERICAN",
    rg: string, 
    cpf: string,
    email: string, 
    motherName: string, 
    phone: string,
    city: string, 
    postalCode: string, 
    street: string, 
    neighborhood: string,
    workCard: string,
    pisPasep: string,
    typeEmployment: "" | "CLT" | "CNPJ" | "FREELANCE",
    laborModality: "" | "IN_PERSON" | "HYBRID" | "HOME_OFFICE",
    laborScale: "" | "_5X2" | "_4X3" | "_6X1",
    admissionDate: string,
    salary: null | number,
    residentialProve: string,
    reservist: boolean,
    documentation: string,
    bank: "" | "SANTANDER" | "SICRED" | "BANCO_DO_BRASIL",
    agency: null | number,
    account: null | number,
    pix: string,
    transportationVoucher: boolean,
    cnpjTransportationVoucher: string,
    monthlyAmount: null | number,
    additionalDocuments: string,
    department: "" | "RESEARCH_AND_DEVELOPMENT" | "WEB_DESIGN" | "PAID_TRAFFIC",
    operation: "" | "_01" | "_02" | "_03",
    level: "" | "PUPPY" | "ASSISTANT" | "JUNIOR",
    status: "ACTIVE" | "INACTIVE",
    quitDate: string
}